.de FN
\fI\|\\$1\|\fP
..
.TH ux 1 "2005 Dec 8" ux
.SH NAME
ux  \- micro-X-editor
.SH SYNTAX
.B "ux <FILENAME>[:line-number]
.PP
<FILENAME> is NOT optional. 
.PP
[:line-number] Start editor at the optional (grep output format) line-number.
No space between <FILENAME> and :line-number.

.SH DESCRIPTION
.I ux
is an ASCII text file editor designed for minimal binary size. It was
written to fullfill a need for a basic, simple, functional, X-windows,
reference text editor, using only libc and libX11.so. \fIux\fP supports files
up to 1 MB, exact match search for strings, goto line number, mouse cursor
positioning, marked block, undo, cut, copy and paste. The main window consists
of two parts: status line showing line number, coloumn, modified flag ('*'
indicates modified), hex value of last key, prompted strings and help access;
and text area. Default text area size is 80 characters by 24 lines. Window
resizing with the mouse is available.

.SH MARKED BLOCKS
A marked block may be selected either with a left mouse click_and_drag or
shift cursor navigation keys. The resulting marked block may be deleted by
the next ASCII character, with the Delete key, or copied to the X
clipboard with Ctrl-Ins or cut to the X clipboard with Shift-Del. Any non
shifted navigation keys or left mouse click will unmark the block.

.PP
A right mouse click_and_drag will highlight and copy the marked text to
the X clipboard. The marked block becomes unmarked upon release of the right
mouse button. To paste, left click to position the cursor to the desired
location, then right click, without moving the mouse, to paste from the X
clipboard.

.PP
A right click of the mouse will also position the cursor under the mouse click
and paste from the X clipboard to the new position of the cursor.

.PP
Shift-Ins will paste from the X clipboard to the current cursor position.

.PP
For either a right mouse click or Shift-Ins operation, if a block is marked,
the marked block will be deleted and then the paste operation will occur at
the position of the deleted text.

.SH KEYS
At any prompted input you can hit the Esc key to cancel the operation. Other
bindings are:

.PP
.IP "<--"
(left arrow) Move left one character.
.PP
.IP "-->"
(right arrow) Move right one character.
.PP
.IP "/\\\\"
(up arrow) Move up one line.
.PP
.IP "\\\/"
(down arrow) Move down one line.
.PP
.IP "Ctrl <--"
(control left arrow) Move to beginning of word left.
.PP
.IP "Ctrl -->"
(control right arrow) Move to beginning of word right.
.PP
.IP "Home"
Move to beginning of line.
.PP
.IP "End"
Move to end of line.
.PP
.IP "PageUp"
Move cursor text-area-height-1 lines up.
.PP
.IP "PageDown"
Move cursor text-area-height-1 lines down.
.PP
.IP "Ctrl Home"
Move to Top of file.
.PP
.IP "Ctrl End"
Move to Bottom of file.
.PP
.IP "Delete"
Delete character under cursor.
.PP
.IP "Backspace"
Delete character before cursor.
.PP
.IP "Ctrl-Y"
Delete from cursor to end of line. If at line end, delete line end.
.PP
.IP "Ctrl-U"
Undo previous insert/delete character operations, one at a time. When undo
buffer is empty, text is in original format, unmodified, as indicated by lack
of a '*' on the status line.
.PP
.IP "F2"
Write file. No backup made. Undo buffer reset to empty.
.PP
.IP "Ctrl-F"
Find string. During search string prompted input, both Backspace and Ctrl-H
remove the character before the string end. New search strings require
backspacing to the start of the old search string. To stop find string input
without searching, enter Esc. To start the find operation, press either Enter
or Ctrl-F. The previous search string is retained so search again is Ctrl-F
Ctrl-F. A find operation will position the cursor at the start of the found
string, indicated by a marked block, or at the bottom of the file if the
string is not found.

.PP
.IP "Ctrl-J"
Jump to line number. During prompted input, specify the new line number in
decimal. Input editing as in 'Find string', above.

.PP
.IP "Shift Del"
Cut marked block to clipboard.
.PP
.IP "Ctrl Ins"
Copy marked block to clipboard.
.PP
.IP "Shift Ins"
Paste from clipboard.

.PP
.IP "F1"
Display help message screen. Press any key to continue.
.PP
.IP "Ctrl-Q"
Quit. If file has been modified you will be prompted to save and exit or
to lose changes and exit. An Esc will return to ux.

.SH ERRORS
.PP
Error return values and meaning:
.PP
0: no error, normal operation.
.PP
1: no filename specified.
.PP
2: Cant open X DISPLAY.
.PP
3: Cant load X font.
.PP
4: Cant allocate window hints.

.SH BUGS
.PP
\fIux\fP uses an exact string match search. Promted string input has no
visible cursor.

.PP
Characters past the displayed width are not displayed. Truncate to shorter
lengths using the Enter key or resize the window.

.PP
There are no scrollbars or menus.

.SH WARRANTY
.PP
This software comes with no warranties or binaries. Compile and use at your
own risk.

.SH AUTHOR AND COPYRIGHT
.PP
The author of \fIux\fP is Terry Loveall <loveall@iinet.com>. Feel free to
e-mail me for any problems, suggestions and bug reports. \fIux\fP is released
into the Public Domain.
